[package]
name = "askhostname"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
ipnet = "2.9.0"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
