[package]
name = "askhostname"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
ipnet = "2.9.0"
tokio = { version = "1.40.0", features = ["full"] }
